### ISSUE TITLE
redis에 하나의 값만 저장되는 오류

### ISSUE THREAD

**Issue by YeomJaeSeon** [Wanted-Free-Pre-Onboarding-Course-10/Assignment3#21]
## 발생 일시
- 11.9
## 발생 위치
- autocompleteService
## 증상
- 레디스 value 타입이 string 이라 값이 하나밖에 저장안되고있었음
## 재현 방법
- set -> sadd를 통해 set구현

**Comment by earthkingman** [comment]
GOOD
